<#import "/spring.ftl" as spring/>
<link href="<@spring.url '/assets/fontawesome-free/css/all.min.css'/>" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
<link href="<@spring.url '/assets/sb-admin/css/sb-admin-2.min.css'/>" rel="stylesheet">
<link href="<@spring.url '/assets/seinab/backend.css'/>" rel="stylesheet">